---
- name: Install Docker Compose via PIP
  pip: name=docker-compose

- name:
  file:
    path="/usr/local/bin/docker-compose"
    state=file
    mode=0755
    owner={{ docker_user }}
    group=docker
